### PR TITLE
Add a function that get's the path of the executable.

### PR DESCRIPTION
**Pull request by jameskerr**
This will be very useful for our brim tests.

### CODE REVIEW

**Comment by nwt** [comment]
@jameskerr: I'd like minimize the amount of JavaScript here. Can this go in brimdata/brim instead?

**Comment by mattnibs** [comment]
@jameskerr I echo @nwt comment. Can this logic go in brim?

**Comment by jameskerr** [comment]
Yeah sure it can go in brim. But having this here would be very convenient. Might I ask why you'd like to not have too much javascript in here?

**Comment by jameskerr** [comment]
Why don't we have a talk at the meeting tomorrow about the zed executables and how they get consumed. There have been several solutions without holistic thoughts behind them. I'm sure there's a good way forward.

**Comment by jameskerr** [comment]
I am closing this in favor of a more thoughtful solution we will think of later.

**Pull request closed without merging**
