### PR TITLE
zio/zngio: process compressed blocks concurrently in scanner

### LINKED ISSUE #2348: Multi-threaded ZNG scanner

### PR DESCRIPTION
**Pull request by nwt**
Improve ZNG scanner performance by processing compressed value message
blocks concurrently.  The scanner creates GOMAXPROCS goroutines.
Goroutine hold a lock while reading and processing ZNG messages with two
exceptions: value messages are partially processed without the lock and
compressed value message blocks are fully processed without it.

Closes #2348.

### CODE REVIEW

**Comment by nwt** [comment]
Here's what I see on my laptop. `conn.zng` is gs://looky-files/sampledata/wrccdc/zeek-logs/conn.log.gz converted to ZNG and is 21 GB (22245027356 B).

Branch main` at d1d77d96d87b40993a9f57fd016b9002aca08de0:
```sh
$ make build && for i in 1 2 3 4 5; do /usr/bin/time ./dist/zq -validate=false boyermooreforthewin conn.zng > /dev/null; done
       38.59 real        32.76 user         5.10 sys
       39.64 real        33.60 user         5.51 sys
       38.97 real        33.16 user         5.26 sys
       39.17 real        33.23 user         5.35 sys
       39.35 real        33.33 user         5.43 sys
````

Branch zngio-scanner-goroutines at 815002f89f3f1f8b7e2f01fb5ff3ccf8e53dc76e:
```sh
$ make build && for i in 1 2 3 4 5; do /usr/bin/time ./dist/zq -validate=false boyermooreforthewin conn.zng > /dev/null; done
       15.49 real        49.77 user        12.13 sys
       16.55 real        52.31 user        13.18 sys
       16.51 real        53.32 user        13.18 sys
       16.72 real        54.39 user        13.31 sys
       18.96 real        57.82 user        14.97 sys
```

**Review by mccanne — APPROVED** [review]
Merge pending tests we discussed...

**Comment by nwt** [comment]
1db68208a0eef3f82c4c8fba6f9ad0e8acdddfda adds a test that scans multiple streams with unique contexts to verify that concurrent accesses to the reader's mapper and stream context are correct. It survives `go test -race`.

**Comment by mccanne** [comment]
Cool!

**Pull request merged**
